[2024-12-03 15:45:05] INFO - train: Starting training process...
[2024-12-03 15:45:05] INFO - train: Loading configurations...
[2024-12-03 15:45:06] INFO - train: Using device: cuda
[2024-12-03 15:45:06] INFO - train: Creating data loaders...
[2024-12-03 15:45:06] ERROR - train: An error occurred: 'name'
Traceback (most recent call last):
  File "/nas2/jieui/class/deepnlp/project/scripts/train.py", line 48, in main
    dataset_name=dataset_config['name'],
KeyError: 'name'
